### deep learning basic

In [21]:
! pip install numpy tensorflow pandas
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd

Requirement already satisfied: numpy in ./lib/python3.13/site-packages (2.5.3)
Requirement already satisfied: tensorflow in ./lib/python3.13/site-packages (2.21.0)
Requirement already satisfied: pandas in ./lib/python3.13/site-packages (3.0.6)
Requirement already satisfied: absl-py>=1.0.0 in ./lib/python3.13/site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in ./lib/python3.13/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in ./lib/python3.13/site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in ./lib/python3.13/site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in ./lib/python3.13/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in ./lib/python3.13/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in ./lib/python3.13/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in ./lib/python3.13/site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in ./lib/python3.13/site-packages (from tensorflow) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in ./lib/python3.13/site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in ./lib/python3.13/site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in ./lib/python3.13/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in ./lib/python3.13/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in ./lib/python3.13/site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in ./lib/python3.13/site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./lib/python3.13/site-packages (from tensorflow) (1.84.0)
Requirement already satisfied: keras>=3.12.0 in ./lib/python3.13/site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in ./lib/python3.13/site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in ./lib/python3.13/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in ./lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in ./lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in ./lib/python3.13/site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in ./lib/python3.13/site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in ./lib/python3.13/site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in ./lib/python3.13/site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./lib/python3.13/site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./lib/python3.13/site-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in ./lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [22]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [23]:
df.head()

   soil_moisture  temperature_c  sunlight_hours  needs_water
0           0.10             34               9            1
1           0.15             30               8            1
2           0.20             26               7            1
3           0.25             22               4            0
4           0.40             28               8            0

In [24]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [25]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [26]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [27]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [28]:
!pip install scikit-learn
from sklearn.model_selection import train_test_split

# splitting the data set 
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

Requirement already satisfied: scikit-learn in ./lib/python3.13/site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in ./lib/python3.13/site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in ./lib/python3.13/site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in ./lib/python3.13/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in ./lib/python3.13/site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./lib/python3.13/site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in ./lib/python3.13/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [36]:
X_train.shape

(12, 3)

In [37]:
# model training 
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [39]:
model.compile(optimizer='sgd',loss="binary_crossentropy",metrics=["accuracy"])

In [42]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,
    batch_size = 4,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7500 - loss: 0.6184 - val_accuracy: 1.0000 - val_loss: 0.6209
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6178 - val_accuracy: 1.0000 - val_loss: 0.6202
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.6172 - val_accuracy: 1.0000 - val_loss: 0.6195
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.6170 - val_accuracy: 1.0000 - val_loss: 0.6190
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.6159 - val_accuracy: 1.0000 - val_loss: 0.6183
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.6158 - val_accuracy: 1.0000 - val_loss: 0.6177
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7500 - loss: 0.6148 - val_accuracy: 1.0000 - val_loss: 0.6170
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6147 - val_accuracy: 1.0000 - val_loss: 0.6164
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.6158 - val_accuracy: 1.0000 - val_loss: 0.6159
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6140 - val_accuracy: 1.0000 - val_loss: 0.6153
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.6132 - val_accuracy: 1.0000 - val_loss: 0.6146
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.6125 - val_accuracy: 1.0000 - val_loss: 0.6139
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6129 - val_accuracy: 1.0000 - val_loss: 0.6132
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6109 - val_accuracy: 1.0000 - val_loss: 0.6124
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.6103 - val_accuracy: 1.0000 - val_loss: 0.6118
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.6097 - val_accuracy: 1.0000 - val_loss: 0.6111
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6099 - val_accuracy: 1.0000 - val_loss: 0.6105
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6095 - val_accuracy: 1.0000 - val_loss: 0.6098
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6099 - val_accuracy: 1.0000 - val_loss: 0.6092
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6077 - val_accuracy: 1.0000 - val_loss: 0.6086
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.6074 - val_accuracy: 1.0000 - val_loss: 0.6080
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6067 - val_accuracy: 1.0000 - val_loss: 0.6073
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6056 - val_accuracy: 1.0000 - val_loss: 0.6067
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6051 - val_accuracy: 1.0000 - val_loss: 0.6061
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6054 - val_accuracy: 1.0000 - val_loss: 0.6054
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6044 - val_accuracy: 1.0000 - val_loss: 0.6046
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6046 - val_accuracy: 1.0000 - val_loss: 0.6040
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6033 - val_accuracy: 1.0000 - val_loss: 0.6033
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6030 - val_accuracy: 1.0000 - val_loss: 0.6028
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6044 - val_accuracy: 1.0000 - val_loss: 0.6020
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6032 - val_accuracy: 1.0000 - val_loss: 0.6014
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6010 - val_accuracy: 1.0000 - val_loss: 0.6008
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6017 - val_accuracy: 1.0000 - val_loss: 0.6002
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5997 - val_accuracy: 1.0000 - val_loss: 0.5994
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5994 - val_accuracy: 1.0000 - val_loss: 0.5988
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.6002 - val_accuracy: 1.0000 - val_loss: 0.5980
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5977 - val_accuracy: 1.0000 - val_loss: 0.5972
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5975 - val_accuracy: 1.0000 - val_loss: 0.5966
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5974 - val_accuracy: 1.0000 - val_loss: 0.5961
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.5964 - val_accuracy: 1.0000 - val_loss: 0.5955
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5962 - val_accuracy: 1.0000 - val_loss: 0.5949
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5949 - val_accuracy: 1.0000 - val_loss: 0.5942
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5958 - val_accuracy: 1.0000 - val_loss: 0.5935
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5939 - val_accuracy: 1.0000 - val_loss: 0.5929
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5938 - val_accuracy: 1.0000 - val_loss: 0.5922
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.5932 - val_accuracy: 1.0000 - val_loss: 0.5917
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5925 - val_accuracy: 1.0000 - val_loss: 0.5911
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5920 - val_accuracy: 1.0000 - val_loss: 0.5903
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5906 - val_accuracy: 1.0000 - val_loss: 0.5895
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5910 - val_accuracy: 1.0000 - val_loss: 0.5891
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5899 - val_accuracy: 1.0000 - val_loss: 0.5884
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5889 - val_accuracy: 1.0000 - val_loss: 0.5878
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5892 - val_accuracy: 1.0000 - val_loss: 0.5872
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5887 - val_accuracy: 1.0000 - val_loss: 0.5864
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5877 - val_accuracy: 1.0000 - val_loss: 0.5858
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5889 - val_accuracy: 1.0000 - val_loss: 0.5853
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5881 - val_accuracy: 1.0000 - val_loss: 0.5848
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5879 - val_accuracy: 1.0000 - val_loss: 0.5840
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5861 - val_accuracy: 1.0000 - val_loss: 0.5832
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5851 - val_accuracy: 1.0000 - val_loss: 0.5827
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5842 - val_accuracy: 1.0000 - val_loss: 0.5821
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5846 - val_accuracy: 1.0000 - val_loss: 0.5813
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5846 - val_accuracy: 1.0000 - val_loss: 0.5805
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.5827 - val_accuracy: 1.0000 - val_loss: 0.5801
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5825 - val_accuracy: 1.0000 - val_loss: 0.5795
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5837 - val_accuracy: 1.0000 - val_loss: 0.5790
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5813 - val_accuracy: 1.0000 - val_loss: 0.5785
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5805 - val_accuracy: 1.0000 - val_loss: 0.5778
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.5795 - val_accuracy: 1.0000 - val_loss: 0.5770
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5791 - val_accuracy: 1.0000 - val_loss: 0.5764
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5804 - val_accuracy: 1.0000 - val_loss: 0.5757
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.5779 - val_accuracy: 1.0000 - val_loss: 0.5752
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5778 - val_accuracy: 1.0000 - val_loss: 0.5745
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5769 - val_accuracy: 1.0000 - val_loss: 0.5738
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8333 - loss: 0.5762 - val_accuracy: 1.0000 - val_loss: 0.5731
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5757 - val_accuracy: 1.0000 - val_loss: 0.5723
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.7500 - loss: 0.5750 - val_accuracy: 1.0000 - val_loss: 0.5718
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8333 - loss: 0.5744 - val_accuracy: 1.0000 - val_loss: 0.5713
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7500 - loss: 0.5739 - val_accuracy: 1.0000 - val_loss: 0.5707
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7500 - loss: 0.5733 - val_accuracy: 1.0000 - val_loss: 0.5698
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5733 - val_accuracy: 1.0000 - val_loss: 0.5693
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5726 - val_accuracy: 1.0000 - val_loss: 0.5687
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5730 - val_accuracy: 1.0000 - val_loss: 0.5682
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5704 - val_accuracy: 1.0000 - val_loss: 0.5674
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5705 - val_accuracy: 1.0000 - val_loss: 0.5667
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5704 - val_accuracy: 1.0000 - val_loss: 0.5662
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5693 - val_accuracy: 1.0000 - val_loss: 0.5655
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8333 - loss: 0.5701 - val_accuracy: 1.0000 - val_loss: 0.5649
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5681 - val_accuracy: 1.0000 - val_loss: 0.5645
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5680 - val_accuracy: 1.0000 - val_loss: 0.5638
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5674 - val_accuracy: 1.0000 - val_loss: 0.5633
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5657 - val_accuracy: 1.0000 - val_loss: 0.5627
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5646 - val_accuracy: 1.0000 - val_loss: 0.5620
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5652 - val_accuracy: 1.0000 - val_loss: 0.5613
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8333 - loss: 0.5650 - val_accuracy: 1.0000 - val_loss: 0.5607
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5630 - val_accuracy: 1.0000 - val_loss: 0.5601
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5624 - val_accuracy: 1.0000 - val_loss: 0.5594
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7500 - loss: 0.5632 - val_accuracy: 1.0000 - val_loss: 0.5589
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5611 - val_accuracy: 1.0000 - val_loss: 0.5584
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5629 - val_accuracy: 1.0000 - val_loss: 0.5576